### ISSUE TITLE
启动的时候出错

### ISSUE THREAD

**Issue by developerworks** [pookpal/star-initReact-example#3]
```
➜  star-initReact-example git:(master) ✗ node -v
v6.9.1
➜  star-initReact-example git:(master) ✗ npm run build:i18n-js

> react-pookpal@1.0.0 build:i18n-js /Users/hezhiqiang/tmp/antd/star-initReact-example
> npm run build:i18n-messages && babel-node --presets es2015 scripts/translate.js


> react-pookpal@1.0.0 build:i18n-messages /Users/hezhiqiang/tmp/antd/star-initReact-example
> rimraf i18n-messages && BABEL_ENV=i18n babel --quiet src > /dev/null

ReferenceError: Unknown plugin "antd" specified in "/Users/hezhiqiang/tmp/antd/star-initReact-example/.babelrc" at 0, attempted to resolve relative to "/Users/hezhiqiang/tmp/antd/star-initReact-example"
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
    at Array.map (native)
    at Function.normalisePlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
    at File.initOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/babel-cli/lib/babel/util.js:52:22)
    at Object.compile (/usr/local/lib/node_modules/babel-cli/lib/babel/util.js:61:12)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:i18n-messages"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-pookpal@1.0.0 build:i18n-messages: `rimraf i18n-messages && BABEL_ENV=i18n babel --quiet src > /dev/null`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-pookpal@1.0.0 build:i18n-messages script 'rimraf i18n-messages && BABEL_ENV=i18n babel --quiet src > /dev/null'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-pookpal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf i18n-messages && BABEL_ENV=i18n babel --quiet src > /dev/null
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-pookpal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-pookpal
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hezhiqiang/tmp/antd/star-initReact-example/npm-debug.log

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:i18n-js"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-pookpal@1.0.0 build:i18n-js: `npm run build:i18n-messages && babel-node --presets es2015 scripts/translate.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-pookpal@1.0.0 build:i18n-js script 'npm run build:i18n-messages && babel-node --presets es2015 scripts/translate.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-pookpal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:i18n-messages && babel-node --presets es2015 scripts/translate.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-pookpal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-pookpal
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hezhiqiang/tmp/antd/star-initReact-example/npm-debug.log
➜  star-initReact-example git:(master) ✗ npm -v
3.10.8

```

**Comment by pookpal** [comment]
请先安装  rimraf 和  babel-plugin-antd，我找个时间重新修改下这个项目

**Comment by pookpal** [comment]
已经全部优化
